package com.zy.pagehelper.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
* Created by Mybatis Generator 2020/11/12
*/
@Data
public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createdDate
     *
     * @mbg.generated
     */
    private Date createddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.lastModifiedDate
     *
     * @mbg.generated
     */
    private Date lastmodifieddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.isSystem
     *
     * @mbg.generated
     */
    private Boolean issystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.permissions
     *
     * @mbg.generated
     */
    private String permissions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createddate=").append(createddate);
        sb.append(", lastmodifieddate=").append(lastmodifieddate);
        sb.append(", version=").append(version);
        sb.append(", description=").append(description);
        sb.append(", issystem=").append(issystem);
        sb.append(", name=").append(name);
        sb.append(", permissions=").append(permissions);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}